// LICENSE NOTICE ==================================================================================

/**
 * netzhaut - Web Browser Engine
 * Copyright (C) 2020 The netzhaut Authors
 * Published under LGPLv3
 */

// INCLUDE =========================================================================================

#include "Unicode.h"
#include "Util.h"

#include "../Common/Macro.h"

#include SELFMAKE_FLOW
#include SELFMAKE_DEFAULT_CHECK

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

// DECLARE =========================================================================================

#define SELFMAKE_LICENSE_NOTICE \
    "/**\n * netzhaut - Web Browser Engine\n * Copyright (C) 2020 The netzhaut Authors\n * Published under LGPLv3\n *\n * This file was generated by the nhmake Library\n */\n\n"

// BUILD ===========================================================================================

// http://unicode.org/Public/
static SELFMAKE_RESULT selfmake_createUnicodeLookupSource(
    NH_BYTE *bytes_p, FILE *File_p, int *count1_p, int *count2_p)
{
SELFMAKE_BEGIN()

    fprintf(File_p, "// LICENSE NOTICE ==================================================================================\n\n");
    fprintf(File_p, SELFMAKE_LICENSE_NOTICE);

    fprintf(File_p, "// INCLUDE =========================================================================================\n\n");
    fprintf(File_p, "#include \"UnicodeLookup.h\"\n\n");

    long lines = 1;
    for (int i = 0; bytes_p[i] != '\0'; ++i) {
        if (bytes_p[i] == '\n') {++lines;}
    }

    fprintf(File_p, "// LOOKUP ==========================================================================================\n\n");
    fprintf(File_p, "const NH_BYTE NH_UNICODE_LOOKUP_PP[%d][255] = \n{\n", lines);

    char *line_p = bytes_p;
    long expectedCodepoint = 0, currentEmpty = 0;
    long empty_pp[2048][2] = {0};

    for (int i = 0; bytes_p[i] != '\0'; ++i) 
    {
        if (bytes_p[i] == '\n') 
        {
            bytes_p[i] = '\0';
            long currentCodepoint = strtol(line_p, NULL, 16);
            if (currentCodepoint != expectedCodepoint) {
                empty_pp[currentEmpty][0] = expectedCodepoint;
                empty_pp[currentEmpty++][1] = currentCodepoint - 1;
                expectedCodepoint = currentCodepoint + 1;
            }
            else {expectedCodepoint++;}
            fprintf(File_p, "    \"%s\",\n", line_p);
            bytes_p[i] = '\n';
            line_p = &bytes_p[i + 1];
        }
    }

    fprintf(File_p, "};\n\n");
    fprintf(File_p, "// UNDEFINED RANGES ================================================================================\n\n");
    fprintf(File_p, "const long NH_UNICODE_LOOKUP_UNDEFINED_RANGES_PP[%d][2] = \n{\n", currentEmpty);

    for (int i = 0; i < currentEmpty; ++i) {
        fprintf(File_p, "    {%d, %d}, \n", empty_pp[i][0], empty_pp[i][1]);
    }

    fprintf(File_p, "};\n\n");

    *count1_p = lines;
    *count2_p = currentEmpty;

SELFMAKE_DIAGNOSTIC_END(SELFMAKE_SUCCESS)
}

static SELFMAKE_RESULT selfmake_createUnicodeLookupHeader(
    FILE *File_p, int count1, int count2)
{
SELFMAKE_BEGIN()

    fprintf(File_p, "#ifndef NH_UNICODE_LOOKUP_H\n");
    fprintf(File_p, "#define NH_UNICODE_LOOKUP_H\n\n");
    fprintf(File_p, "#ifndef DOXYGEN_SHOULD_SKIP_THIS\n\n");

    fprintf(File_p, SELFMAKE_LICENSE_NOTICE);

    fprintf(File_p, "#include \"String.h\"\n\n");
    fprintf(File_p, "#endif\n\n");

    fprintf(File_p, "/** @addtogroup nhcoreMacros\n *  @{\n */\n\n");

    fprintf(File_p, "    #define NH_UNICODE_LOOKUP_COUNT %d\n", count1);
    fprintf(File_p, "    #define NH_UNICODE_LOOKUP_UNDEFINED_RANGES_COUNT %d\n\n", count2);

    fprintf(File_p, "/** @} */\n\n");
    fprintf(File_p, "/** @addtogroup nhcoreVars\n *  @{\n */\n\n");

    fprintf(File_p, "    extern const NH_BYTE NH_UNICODE_LOOKUP_PP[%d][255];\n", count1);
    fprintf(File_p, "    extern const long NH_UNICODE_LOOKUP_UNDEFINED_RANGES_PP[%d][2];\n\n", count2);

    fprintf(File_p, "/** @} */\n\n#endif");

SELFMAKE_DIAGNOSTIC_END(SELFMAKE_SUCCESS)
}

SELFMAKE_RESULT selfmake_createUnicodeLookup() 
{
SELFMAKE_BEGIN()

    char inPath_p[255] = {'\0'};
    sprintf(inPath_p, "%s/src/bin/nhmake/Common/Data/UnicodeData-14.0.0d3.txt", SELFMAKE_PROJECT_DIR_P);

    NH_BYTE *bytes_p = selfmake_getFileData(inPath_p, NULL);
    SELFMAKE_CHECK_NULL(bytes_p)

    char outPath_p[255] = {'\0'};
    sprintf(outPath_p, "%s/src/lib/nhcore/UnicodeLookup.c", SELFMAKE_PROJECT_DIR_P);

    FILE *File_p = fopen(outPath_p, "w");
    SELFMAKE_CHECK_NULL(File_p)

    int count1, count2;
    SELFMAKE_CHECK(selfmake_createUnicodeLookupSource(bytes_p, File_p, &count1, &count2))
    free(bytes_p);
    fclose(File_p);

    outPath_p[strlen(outPath_p) - 1] = 'h';
    File_p = fopen(outPath_p, "w");
    SELFMAKE_CHECK_NULL(File_p)

    SELFMAKE_CHECK(selfmake_createUnicodeLookupHeader(File_p, count1, count2))
    fclose(File_p);

SELFMAKE_DIAGNOSTIC_END(SELFMAKE_SUCCESS)
}

